services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3001"
    volumes:
      - './frontend:/opt/app'
    restart: always
    environment:
      - "CI:'true'"
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - './backend:/opt/app'
    restart: always



# services:
#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "8080:3001"
#     env_file:
#       - .env
#     restart: always
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "5050:5001"
#     env_file:
#       - .env
#     restart: always
    