services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3000:8080"
    env_file:
      - .env
    restart: always

  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "5001:4040"
    env_file:
      - .env
    restart: always
